import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/app/providers/StoreProvider";
import AppHeightsProvider from "@/app/providers/AppHeightsProvider";
import I18nProvider from "./providers/I18nProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <I18nProvider>
            <AppHeightsProvider>{children}</AppHeightsProvider>
          </I18nProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
